version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "base-dev-ec2"
s3_prefix = "base-dev-ec2"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Organization=\"base\" Project=\"ec2\" Env=\"dev\""
image_repositories = []
resolve_s3 = true
